packageExtensions:
  '@nextui-org/snippet@*':
    dependencies:
      framer-motion: '*'
  '@react-aria/overlays@*':
    dependencies:
      react-dom: '*'
  '@nextui-org/ripple@*':
    dependencies:
      framer-motion: '*'

yarnPath: .yarn/releases/yarn-3.6.0.cjs
