packageExtensions:
  "@nextui-org/framer-transitions@*":
    dependencies:
      framer-motion: "*"
  "@nextui-org/tooltip@*":
    dependencies:
      framer-motion: "*"
  "@react-aria/overlays@*":
    dependencies:
      react-dom: "*"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
